In [1]:
import pandas as pd

In [2]:
info={
    "Name" : ["Rahul", "Parag", "Shradha"],
    "Cgpa" : [8.9,9.0,9.7]
}

df=pd.DataFrame(info)
df

      Name  Cgpa
0    Rahul   8.9
1    Parag   9.0
2  Shradha   9.7

In [3]:
s=pd.Series([1,2,3,4,5])
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
'''
in pandas we do not have index or something we have labels
we can make them on our own or a custom labels
we can access through indexing and also with labels that we have given
'''
s=pd.Series([23,24,25,26],index=["Adam","Eve","Bob","Charlie"])
print(s)
print(s["Adam"])

Adam       23
Eve        24
Bob        25
Charlie    26
dtype: int64
23

In [5]:
#properties of series
s1=pd.Series([1,2,3,4,5])
s2=pd.Series([10,20,30,40,50])

print(s1+s2)

s1[0]=100
change_s1=s1.drop(0)
print(s1)
print(change_s1)

0    11
1    22
2    33
3    44
4    55
dtype: int64
0    100
1      2
2      3
3      4
4      5
dtype: int64
1    2
2    3
3    4
4    5
dtype: int64

In [6]:
#DataFrame
info={
    "Name" : ["Rahul", "Parag", "Shradha"],
    "Age" : [25,21,28],
    "Cgpa" : [8.9,9.0,9.7]
}
df=pd.DataFrame(info)
df

      Name  Age  Cgpa
0    Rahul   25   8.9
1    Parag   21   9.0
2  Shradha   28   9.7

In [7]:
#csv data
df=pd.read_csv("employee_data.csv")
print(df,type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [24]:
 #json data
df=pd.read_json("data.json")
print(df,type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [25]:
#DataFrame Methods
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [26]:
# df.head() #starting 5 rows
# df.tail() #ending 5 rows
# df.tail(2) #ending 2 rows
# df.sample(4) #any 4 rows

# df.info()
# df.shape
# df.describe()
df.columns
df.nunique()

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [27]:
#Loading air quality dataset
df=pd.read_csv("globalAirQuality.csv")
#printing the dataset
df

#printing only the first 3 rows
df.head(3)

#printing a specific columns
df[["city", "aqi"]].head(2)

#selecting index and label based rows
# df.loc[2] #label based
# df.loc[0:2] #label based index=inclusive and end idx=inclusive

# df.iloc[0:2] #index based start index=inclusive and end idx=exclusive

df.loc[0,"aqi"]
df.loc[0:10,["city","aqi"]]
df.iloc[0:10,1:5]
# df.describe()

df.columns

Index(['timestamp', 'country', 'city', 'latitude', 'longitude', 'pm25', 'pm10',
       'no2', 'so2', 'o3', 'co', 'aqi', 'temperature', 'humidity',
       'wind_speed'],
      dtype='object')

In [28]:
#filtering of data
# df[(df["aqi"]>100) & (df["temperature"]>30)]
df[(df["aqi"]>100) & (df["temperature"]<30)]

aqi_data=df[(df["aqi"]>100) & (df["temperature"]>30)] [["city","aqi"] ]
aqi_data
aqi_data.iloc[0] # this is possible bcZ it returns the first value of the dataframe
# aqi_data.loc[0] #this cant be done bcz there is no index label named as '0'

city    New York
aqi          155
Name: 6, dtype: object

In [36]:
#filtering using Query() rules
df.query("aqi > 100")

# query()-returns the copy
aqi_val=120
df.query("aqi>100 & temperature>30")[["city","aqi"]]
aqi_data=df.query("aqi> @aqi_val & temperature>30")[["city","aqi"]].copy()
aqi_data.iloc[0]

city    New York
aqi          155
Name: 6, dtype: object

In [14]:
#cleaning the data-Handling missing values

df=pd.read_csv("raw_data.csv")
# df.isnull()
df.isna()

df.isna().sum()

df.dropna()
# df.dropna(axis=1)

df.fillna(0)


cleaned_data=df.copy()

age_mean=cleaned_data["age"].mean()

cleaned_data["age"]=cleaned_data["age"].fillna(age_mean)
# cleaned_data
df.ffill()
df.bfill()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [15]:
#cleaning the data-Handling duplicate values
df.duplicated()
df[["country","gender"]].duplicated()

#dropping duplicates
df2=df.copy() #always store a copy

df.drop_duplicates(inplace=True)

In [16]:
#cleaning the data-Handling datatypes values
#data types
df.dtypes
df2=df.copy()

df2["age"]=df2["age"].fillna(0)
df2["country"]=df2["country"].ffill()
df2["age"]=df2["age"].astype("int64").copy()
df2.dtypes

id           int64
name        object
age          int64
country     object
gender      object
income     float64
dtype: object

In [17]:
aqi_data=pd.read_csv("globalAirQuality.csv")
aqi_data["timestamp"]=pd.to_datetime(aqi_data["timestamp"])

aqi_data["timestamp"].dtype

dtype('<M8[ns]')

In [18]:
date_str=pd.Series([pd.to_datetime("2026-11-20")])
type(date_str.dtypes)

numpy.dtypes.DateTime64DType

In [19]:
#Handling Strings
df ["country"].str.contains("india",case=False)

0     False
2     False
3     False
4     False
5     False
6      True
7       NaN
8     False
9     False
10    False
Name: country, dtype: object

In [20]:
# Feature Engineering
# high order function like -- apply() funtion
df2["tax"]=df2["income"].apply(lambda x: "20%" if x>50000 else "10%")


gender_map={'Male':'M','Female':'F','Unknown':'U'}
df2["gender"]=df2["gender"].map(gender_map)

df2.assign(new_income=df2["income"] * 1.1)

df2 ["country"] = df2["country"].replace("USA","United States")

In [43]:
df3= df2.copy()
new_col_order=[col for col in df3.columns if col !="id"]+["id"]
#print(new_col_order)
df3[new_col_order]

['name', 'age', 'country', 'gender', 'income', 'tax', 'id']

            name  age        country gender   income  tax  id
0       John Doe   29  United States      M  55000.0  20%   1
2     Jane Smith    0         Canada      F  62000.0  20%   2
3           Alex    0  United States      U  47000.0  10%   3
4   Maria Garcia   34          Spain      F      NaN  10%   4
5         Li Wei   27          China      M  51000.0  20%   5
6            NaN   45          India      F  73000.0  20%   6
7     Ahmed Khan   38          India      M  68000.0  20%   7
8     Rachel Lee   29  United States      F  62000.0  20%   8
9    Carlos Ruiz    0         Mexico      M  45000.0  10%   9
10   Emily Davis   31  United States    NaN  58000.0  20%  10

In [46]:
df3=df2.copy()
df3=df3.drop_duplicates()
df3=df3.fillna(0)

df3=df3.sort_values("income")
df3=df3.reset_index(drop=True)

In [48]:
df3.to_csv("sorted_data.csv")

In [52]:
df3.groupby("country")["income"].mean()
df3.groupby("country")["income"].min()
df3.groupby("country")["income"].agg(["mean","min","max"])

                  mean      min      max
country
Canada         62000.0  62000.0  62000.0
China          51000.0  51000.0  51000.0
India          70500.0  68000.0  73000.0
Mexico         45000.0  45000.0  45000.0
Spain              0.0      0.0      0.0
United States  55500.0  47000.0  62000.0

In [55]:
# Melt & Pivot
df = pd.DataFrame({
    "country": ["USA", "USA", "India", "India"],
    "year": [2020, 2021, 2020, 2021],
    "sales": [100, 120, 90, 110],
    "profit": [20, 25, 18, 22],
    "tax":[10,20,30,40]
})
df

  country  year  sales  profit  tax
0     USA  2020    100      20   10
1     USA  2021    120      25   20
2   India  2020     90      18   30
3   India  2021    110      22   40

In [59]:
# lets melt this data
melted_df=df.melt(
    id_vars=["country","year"],
    value_vars=["sales","profit"],
    var_name="metrics",
    value_name="value"
)

In [62]:
melted_df.pivot(
    index=["country","year"],
    columns="metrics",
    values="value"
)

metrics       profit  sales
country year
India   2020      18     90
        2021      22    110
USA     2020      20    100
        2021      25    120